language: python
python:
  - "3.6"
install:
  - "pip install --upgrade pip"
  - "pip install -U pipenv"
  - "pipenv install --dev"
script:
  - make tests
after_success:
  - pip install https://github.com/codecov/codecov-python/tarball/v2.0.6
  - make coverage
