language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r dev-requirements.txt"
script:
  - make tests
after_success:
  - pip install https://github.com/codecov/codecov-python/tarball/v2.0.6
  - make coverage